{% set name = "nanocube" %}
{% set version = "0.2.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nanocube-{{ version }}.tar.gz
  sha256: 5737404f67c8cc1cc05c308a9fc08d04bf0e99568009dd07b1b3c904e8368863
  patches:
    - 0001-get-version.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - VERSION={{ version }}

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - pyroaring
    - pyarrow
    - sortednp
    - lz4
    - zstandard

test:
  imports:
    - nanocube
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Zeutschler/nanocube
  summary: Lightning fast OLAP-style point queries on Pandas DataFrames.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
